### ISSUE TITLE
mergeGGIR fails because of lowercase ID number in ms5.outraw

### ISSUE THREAD

**Issue by TheTS** [habitus-eu/hbGPS#11]
Hi Vincent

I just had a play with the hbGPS package. This is not necessarily a bug in hbGPS, but a bug in GGIR. During the GPS/acc merge, I noticed the `mergeGGIR` function fails because it cannot match the ID number of the accelerometer data:

`(X): GPS ID not found in ACC files`

The ID it is pulling from the ms5.outraw path (using id_loc = 2, up to the underscore) is 'p20296'

`ms5.outraw/40_100_400/p20296_test_NotWorn.csv`

It is pulling the correct ID number. However, the original ID in the accelerometer filename is 'P20296' (e.g., 'P20296_test.cwa')

When GGIR saves the ms5.outraw output, it seems to make the ID lowercase.

I can workaround this by renaming my GPS files to lowercase 'p20296.csv' and it will run.

I had a look in g.part5 but I couldn't see where the 'meta\ms5.outraw\40_120_400\file.csv' files were being saved.

**Comment by vincentvanhees** [comment]
Hi Tom, thanks for testing the package. I think this was fixed with a [recent commit](https://github.com/wadpac/GGIR/commit/27fd3943afbecff545ad456e3bd7148f08d943c0), which is now part of the 3.0-1 release on GitHub. This is not on CRAN as I do not put all GitHub releases on CRAN.

UPDATE: the fix is now part of CRAN release 3.0-2.

**Comment by yeonghohwang** [comment]
Hello,
Thank you for developing the hbGPS package and providing assistance! 

I am continually receiving the warning message "**(X): GPS ID not found in ACC filesNULL**." 

I have **a file processed through GGIR that contains ActiGraph count data**. I also have **GPS raw data file measured with a Qstarz GPS**. 

The wear period for both devices is one week (September 4 - September 10). The accelerometer data has non-wear time and sleep time removed. The GPS data also contains many gaps.

I am now trying to combine these two files using the hbGPS package. However, only the GPS raw data is being processed, and the warning message above appears.

Based on the previous discussion, I checked the filenames first. The accelerometer filename is "**test27_acc_NotWorn**" and the GPS filename is "**test27_gps**." I am using "**idloc = 2**." Despite this, I am still unable to resolve this warning message. I suspect it might be an issue with the timestamps, but I haven't been able to solve it yet. 

Could you kindly guide me on how to merge these two files? Below, I share my commands and also provide the first 10 rows including column names of both test files.

hbGPS(idloc = 2,
      GGIRpath = "C:/Users/Epi/Desktop/ggir",
      gps_file = "C:/Users/Epi/Desktop/hbGPS",
      outputDir = "C:/Users/Epi/Desktop/hbGPSoutput",
      outputFormat = "notPALMS",
      time_format = "%Y/%m/%d %H:%M:%S",
      tz = "America/Edmonton",
      AccThresholds = "default", 
      maxBreakLengthSeconds = 120,
      minTripDur = 60,
      minTripDist_m = 100,
      threshold_snr = 225,
      threshold_snr_ratio = 50)

[test27_acc_NotWorn.csv](https://github.com/user-attachments/files/16473022/test27_acc_NotWorn.csv)

[test27_gps.csv](https://github.com/user-attachments/files/16473023/test27_gps.csv)
