### ISSUE TITLE
GPS file Column Headers Unreadable for SNR calculation

### ISSUE THREAD

**Issue by clsteel** [habitus-eu/hbGPS#12]
QStarz GPS output file column headers (and data) don't always match the formatting expected in load_and_tidy_up_GPS function. SAT INFO column, both data format and column name, can change depending on the options selected upon export. 

- for example, mine included two additional outputs, so my column header is "SAT INFO (SID-ELE-AZI-SNR)" vs expected format of "SAT INFO (SID-SNR)"
- as far as I am aware, SNR is always the final value in the set of values in sat info (when it has been selected at all). 

- Additionally, number of satellite column default format has NO space ("NSAT(USED/VIEW)" is exact output); manually changing my data to match the expected format ("NSAT (USED/VIEW", with a space) fixed an "snr_ratio cannot be calculated" error that I was getting.

**Comment by vincentvanhees** [comment]
Thanks for reporting this!

I have now prepared a fix, in which I am making two assumptions:
- The relevant column header always starts with "SAT INFO", lower case also allowed, regardless of what text follows.
- SNR is at the end of the list, where the list can be of length two or larger. 

Does this make sense to you or are more variations possible?

Further, would you mind trying out the test branch on your data?

`remotes::install_github("habitus-eu/hbGPS", ref = "issue12_gps_col_header_snr")`

**Comment by clsteel** [comment]
Thank you, Vincent! I have a couple of questions: 

I am trying to understand the role of the "Ngroups" in line 9 of signalNoiseRatio--the number of groups in a row is equal to the number of satellites in view; each parenthesis contains the info for one satellite. The last value in the dashed list is the SNR value. So in a hypothetical 
SAT INFO (SID-ELE-AZI-SNR)
(1-1-1-10); (1-1-1-10);(1-1-1-10)

There are three satellites, each of which has an SNR value of 10, so the expected SNR value is 30 for this row. 
I apologize if this is already what your code accomplishes, I just am making sure I understand. The Ngroups and Ndashes is a little hard for me to wrap my head around and I want to be sure it does the same thing if we have a row with satellite info from 17 satellites or if we have 2. 

I have tested the code on my data and I get a console full of "NAs introduced by coercion"--I suspect that the closing parenthesis character is still attached to the value, so the as.numeric in line 13 can't read it? That's what I was finding in my testing. 

Apologies if I'm not explaining this well--please let me know if I didn't make sense anywhere. 

Chelsea

**Comment by vincentvanhees** [comment]
Thank you for your feedback Chelsea, your explanation matches my calculation. I have now revised the code to make it more readable.

> I have tested the code on my data and I get a console full of "NAs introduced by coercion"--I su...

I suspect this is because of the parenthesis, which I did not have in my example, I have now adopted to code to handle those as well.

Prior to this project I had not experience with GPS data, so please be critical about everything you see. (Last week I drafted a narrative description of what happens inside hbGPS, and I asked the research group who hired me to develop hbGPS to review it, hopefully this can be put online soon such that hbGPS is a bit easier to understand).

**Comment by clsteel** [comment]
That's great, Vincent, the comments cleared things up for me. I am still getting the NAs introduced by coercion error and after looking at your GPS input test data I think this is because of the NSAT(USED/VIEW) column--yours is formatted as "5 (7)" and mine is formatted as "5 / 7". Changing the format manually to match fixed that error. 

I look forward to seeing the more detailed writeup of the program! This tool is going to be incredibly useful for my work so I really appreciate you taking the time to address these small things. 

Cheers, 
Chelsea

**Comment by vincentvanhees** [comment]
Oh, that should be easy to automate as well... I will try to do it in the upcoming days, so don't bother modifying all your data.
Generally it is better to adopt software to become more generically applicable to data than to adopt data to software.

Could you send me a test file just in case there are any other differences with the test files I have been working with?

**Comment by clsteel** [comment]
Perfect, thank you--here is a short snippet of a GPS file (with modified coordinates for privacy).
[test_.csv](https://github.com/habitus-eu/hbGPS/files/14348647/test_.csv)

**Comment by vincentvanhees** [comment]
Thanks, should be addressed now. I have prepared a PR: https://github.com/habitus-eu/hbGPS/pull/14 to merge these updates into the main branch after which I will create a new release.

**Comment by vincentvanhees** [comment]
@clsteel 

Update on

> I look forward to seeing the more detailed writeup of the program! 

I added a narrative description of what hbGPS does in https://github.com/habitus-eu/hbGPS/blob/main/documentation.md
and it was referenced in https://link.springer.com/article/10.1186/s12942-024-00373-8
