### ISSUE TITLE
tripDur value short by one epoch length

### ISSUE THREAD

**Issue by clsteel** [habitus-eu/hbGPS#19]
Trip duration values seem to be short one epoch length. For example, hbGPS identified a trip in my GPS data marking 12 rows of 30s epoch data (6 minutes) to be one trip, but tripDur value was 330 rather than expected 360.

**Comment by vincentvanhees** [comment]
Thank you for reporting this, I have not had time yet to look into it. If you are familiar with github and package development then I would welcome active efforts to help improve the repository with pull requests. (edit: I plan to look into it, but need to prioritise paid work first)
