### ISSUE TITLE
Is it possible to run hbGPS without accelerometer data?

### ISSUE THREAD

**Issue by rtsaboya** [habitus-eu/hbGPS#22]
First of all, thanks for this tool!

Would it possible to run hbGPS without accelerometer data, for instance to get only trips' duration, distance and type?

**Comment by vincentvanhees** [comment]
Good question. This actually already works and I justed test it. What you need to do is:

- Point argument `GGIRpath` to an empty folder. It does not matter what folder it is as long as it is empty.
- Make sure argument `outputFormat` is not set to "PALMS", it does not matter what you fill in as long as it is not "PALMS", e.g. "notPALMS".

This will then no longer try to imitate PALMS output format, but should include all the information you need.

As a next step in the hbGPS development we may need to:
- Modify code to also allow for only using GPS data and still allow for imitating PALMS output format.
- Add new input argument to indicate whether GPS recordings without matching ACC should be skipped or not.
- Add documentation for all this.

I cannot promise that I will do this anytime soon as I do not have funding for spending more time on hbGPS at the moment. If you see funding opportunities or know someone with an interest in helping to maintain the repository then pm me (v.vanhees at acceleting.com)

**Comment by rtsaboya** [comment]
Thanks! 
It worked. 
I am looking into this for a colleague, so I don't know if they have funding for this. If they do, I think they will be interested in working with you.
Best,
Renato.
