### ISSUE TITLE
Warning message: (X): GPS ID not found in ACC files

### ISSUE THREAD

**Issue by yeonghohwang** [habitus-eu/hbGPS#23]
Hello,

Thank you for developing the hbGPS package and providing assistance! 

I am continually receiving the warning message "**(X): GPS ID not found in ACC filesNULL**." 

I have **a file processed through GGIR that contains ActiGraph count data**. I also have **GPS raw data file measured with a Qstarz GPS**. 

The wear period for both devices is one week (September 4 - September 10). The accelerometer data has non-wear time and sleep time removed. The GPS data also contains many gaps.

I am now trying to combine these two files using the hbGPS package. However, only the GPS raw data is being processed, and the warning message above appears.

Based on the previous discussion, I checked the filenames first. The accelerometer filename is "**test27_acc_NotWorn**" and the GPS filename is "**test27_gps**." I am using "**idloc = 2**." Despite this, I am still unable to resolve this warning message. I suspect it might be an issue with the timestamps, but I haven't been able to solve it yet. 

Could you kindly guide me on how to merge these two files? 

hbGPS(idloc = 2,
      GGIRpath = "C:/Users/Epi/Desktop/ggir",
      gps_file = "C:/Users/Epi/Desktop/hbGPS",
      outputDir = "C:/Users/Epi/Desktop/hbGPSoutput",
      outputFormat = "notPALMS",
      time_format = "%Y/%m/%d %H:%M:%S",
      tz = "America/Edmonton",
      AccThresholds = "default", 
      maxBreakLengthSeconds = 120,
      minTripDur = 60,
      minTripDist_m = 100,
      threshold_snr = 225,
      threshold_snr_ratio = 50)

_Originally posted by @yeonghohwang in https://github.com/habitus-eu/hbGPS/issues/11#issuecomment-2264306219_

**Comment by vincentvanhees** [comment]
Sorry to hear you are struggling. I see that hbGPS correctly extracts "test27" as ID for this GPS file, which it then tries to recognise in the csv files produced by GGIR. So, I think that part goes well if you specified the correct `gps_file` folder.

Could you check that the `GGIRpath` points at the folder where GGIR stores its output, so not the folder of the GGIR package itself. You may even want to point it specifically at the subfolder meta/ms5.outraw. For example, for one of my project i have:
`GGIRpath = "D:/GPSprocessing/output_studyX/meta/ms5.outraw"`

Further, probably unrelated, I see that `test27_acc_NotWorn.csv` has only 10 lines. I assume you removed the other rows and that the recording is actually a lot longer.

**Comment by yeonghohwang** [comment]
Hello Vincent, 

Thank you so much for your thoughtful response! It has been really helpful.

Yeongho
