### ISSUE TITLE
Question about the "ptid" column

### ISSUE THREAD

**Issue by rtsaboya** [habitus-eu/hbGPS#25]
Hi!
Trying to work with a file with the "ptid" column, I keep getting an error caused by the script not recognizing the right ID. Checking the original code, I think the source of the error may be in line 8 of "load_and_tidy_up_GPS.R"

In this line, shouldn't the index be 1 instead of 7?

https://github.com/habitus-eu/hbGPS/blob/4ee5c5d3a014b85fcb4b934fb1e051d56575462d/R/load_and_tidy_up_GPS.R#L8

Thanks in advance!

**Comment by vincentvanhees** [comment]
Thanks for reaching out.

The comment in line 6 indicates that the if statement is specific to the dataset format from a publication in the MSSE journal (Carlson 2015), which I briefly used at an early stage of the development for testing. Their data file has GPS data from multiple participants in the same csv file. The code reflects me running hbGPS on one of those participants by selecting the 7th unique ID.

It may be best if I comment out these lines as this is not intended as a generic functionality for other users, and its current form confusing.

In the meantime you may want to avoid having 'ptid' as a column name in your files and make sure data from each participant is stored in a separate file.

If you would like that hbGPS is able to handle these type of multi-participant files then that would require more work. You are welcome to do this work and make a pull request. Alternatively, I may have time in January to work on this as a paid consultancy.

**Comment by rtsaboya** [comment]
Ok, thanks for clarifying that!
Best,
Renato.
